/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class TebakAngkaWindow extends javax.swing.JFrame {

    /**
     * Creates new form TebakAngkaWindow
     */
    int angkaSoal = 0;

    public TebakAngkaWindow() {
        initComponents();
        lblHasil.setVisible(false);
        btnCheckAngka.setVisible(false);
        setLocationRelativeTo(this);
        txtInputAngka.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMulai = new javax.swing.JButton();
        lblPetunjuk = new javax.swing.JLabel();
        txtInputAngka = new javax.swing.JTextField();
        btnCheckAngka = new javax.swing.JButton();
        lblHasil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game Tebak Angka");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Pictures\\question.jpg")); // NOI18N

        btnMulai.setText("Mulai");
        btnMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulaiActionPerformed(evt);
            }
        });

        lblPetunjuk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPetunjuk.setText("Klik Tombol Mulai... ");

        btnCheckAngka.setText("Anda Yakin?");
        btnCheckAngka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAngkaActionPerformed(evt);
            }
        });

        lblHasil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHasil.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMulai)
                            .addComponent(txtInputAngka)
                            .addComponent(lblPetunjuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblHasil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCheckAngka)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMulai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPetunjuk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInputAngka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckAngka)
                    .addComponent(lblHasil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulaiActionPerformed
        txtInputAngka.setText("");
        lblHasil.setText("");
        angkaSoal = generateAngka();
        lblPetunjuk.setText("Tebak Angka 1 - 100, dengan Angka yang MENGANDUNG = " + String.valueOf(angkaSoal).charAt(0));
        btnCheckAngka.setVisible(true);
        txtInputAngka.setEditable(true);
    }//GEN-LAST:event_btnMulaiActionPerformed

    private void btnCheckAngkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAngkaActionPerformed
        try {
            String tebakan = txtInputAngka.getText();
            int jawaban = Integer.parseInt(tebakan);
            if (jawaban == angkaSoal) {
                lblHasil.setVisible(true);
                lblHasil.setText("Anda Luar Biasa...! Angka yang ditebak adalah " + angkaSoal);
                lblPetunjuk.setText("Tebak Angka 1 - 100, dengan Angka yang MENGANDUNG = "+angkaSoal);
                txtInputAngka.setEditable(false);
            } else {
                if (jawaban > angkaSoal) {
                    lblHasil.setVisible(true);
                    lblHasil.setText("Angka yang ditebak LEBIH KECIL dari " + jawaban);
                } else if (jawaban < angkaSoal) {
                    lblHasil.setVisible(true);
                    lblHasil.setText("Angka yang ditebak LEBIH BESAR dari " + jawaban);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Masukan ANGKA Brooo jangan HURUF...!");
        }
    }//GEN-LAST:event_btnCheckAngkaActionPerformed

    private int generateAngka() {
        double random = Math.random() * 100;
        double ceilValue = Math.ceil(random);
        int generateAngkaSoal = (int) ceilValue;
        return generateAngkaSoal;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TebakAngkaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TebakAngkaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TebakAngkaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TebakAngkaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TebakAngkaWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckAngka;
    private javax.swing.JButton btnMulai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblPetunjuk;
    private javax.swing.JTextField txtInputAngka;
    // End of variables declaration//GEN-END:variables
}
